### PR TITLE
Support for Laravel 9.x

### PR DESCRIPTION
**Pull request by ConnySjoblom**
Support for Laravel 9.x

### CODE REVIEW

**Comment by ConnySjoblom** [comment]
Resolves #51

**Review by samiheikki — APPROVED** [review]

**Review by leorimmer — APPROVED** [review]

**Review by PetroSilenius — APPROVED** [review]

**Review by limonte — APPROVED** [review]

**Comment by llomgui** [comment]
Hello,

Do you need something/someone to merge this PR?

**Comment by ConnySjoblom** [comment]
We actually didn't use anything else than the mailer from this package, so what we ended up doing, is removing this one, and instead using https://github.com/symfony/mailjet-mailer directly like this https://laravel.com/docs/9.x/mail#additional-symfony-transports

**Comment by lukeptchr** [comment]
Could someone please merge this? I actually need the mailjet client..

**Pull request merged**
